spring.application.name=account-management
server.port=8012
spring.main.banner-mode=off
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.org.springframework.security=warn
logging.level.reactor.netty=warn

eureka.client.service-url.defaultZone=http://localhost:8010/eureka/
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true