spring.application.name=Eureka
server.port=8010
spring.main.banner-mode=off
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.org.springframework.security=warn
logging.level.reactor.netty=warn

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false