spring.application.name=apiGateway
server.port=8011
spring.main.banner-mode=off
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.org.springframework.security=warn
logging.level.reactor.netty=warn

eureka.client.service-url.defaultZone=http://localhost:8010/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=login
spring.cloud.gateway.server.webflux.routes[0].uri=lb://users
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/login
spring.cloud.gateway.server.webflux.routes[0].predicates[1]=Method=POST
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=0

spring.cloud.gateway.server.webflux.routes[1].id=users-secure
spring.cloud.gateway.server.webflux.routes[1].uri=lb://users
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=AuthorizationHeaderFilter
